apiVersion: v1
kind: Secret
metadata:
  name: auth-env
  namespace: auth-service
type: Opaque
stringData:
  DATABASE_URL: "postgresql://admin:admin123@auth-db.auth-service.svc.cluster.local:5432/auth"
  SECRET_KEY: "supersecretkey"
