apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-postgres
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/tylermac92/k8s-microservices-stack
    targetRevision: HEAD
    path: manifests/auth-service/postgres/postgresql
    helm:
      valueFiles:
        - ../values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: auth-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
