apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user-service
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/tylermac92/k8s-microservices-stack
    targetRevision: HEAD
    path: manifests/user-service
  destination:
    server: https://kubernetes.default.svc
    namespace: user-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
